
### Login
POST https://web-gdss.vercel.app/api/auth/login
Content-Type: application/json

{
    "email":"arham@gmail.com",
    "password":"password2"
}

### Register
POST https://web-gdss.vercel.app/api/auth/register
Content-Type: application/json

{
    "nama":"Adam Fatin",
    "email":"adam@gmail.com",
    "password":"password",
    "peran":"Decision Maker 1"
}

### Logout
POST https://web-gdss.vercel.app/api/auth/logout

### Refresh Access Token
POST https://web-gdss.vercel.app/api/auth/refresh 

### Token
@accessToken= eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF91c2VyIjoiNjkxYTBhYzc0NzFmMjkxYzViYzgxOGMzIiwiZW1haWwiOiJhZGFtQGdtYWlsLmNvbSIsImlhdCI6MTc2MzMxNzA4MiwiZXhwIjoxNzYzMzIwNjgyfQ.dondgQOWfWRP5PThhkRWyrh3h59vEEGSnK3fC0uLUAI

### Dashboard
GET https://web-gdss.vercel.app/api/
Authorization: Bearer {{accessToken}}



### Get User By Id
GET https://web-gdss.vercel.app/api/user/find?id_user=6910cb902e5b13934a3a9b67
Authorization: Bearer {{accessToken}}

### Get Total User
GET https://web-gdss.vercel.app/api/user/total
Authorization: Bearer {{accessToken}}

### Update User By Id   
PUT https://web-gdss.vercel.app/api/user
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "id_user":"69109c6a6a0c7a5786f4c696",
    "nama":"Nachsyas Arham Mumtaz",
    "email":"arham@gmail.com",
    "peran":"Decision Maker 1"
}

### Create New User
POST https://web-gdss.vercel.app/api/user
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "nama":"Reza Kurnia",
    "email":"reza@gmail.com",
    "password":"password",
    "peran":"Decision Maker 4"
}

### Delete User
DELETE https://web-gdss.vercel.app/api/user?id_user=6910cb372e5b13934a3a9b56
Authorization: Bearer {{accessToken}}

### Update Password
POST https://web-gdss.vercel.app/api/user/password
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "id_user":"69109c6a6a0c7a5786f4c696",
    "password":"password2"
}



### Get Total Alternatif
GET https://web-gdss.vercel.app/api/alternatif/total
Authorization: Bearer {{accessToken}}

### Add Alternatif
POST https://web-gdss.vercel.app/api/alternatif
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "nama":"Mie Titi Panakkukang",
    "deskripsi":"Mie kering khas Makassar favorit wisatawan."
}

### Update Alternatif
PUT https://web-gdss.vercel.app/api/alternatif
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "id_alternatif":"69117a7691a69d09370572a1",
    "nama":"Sop Saudara Irian",
    "deskripsi":"Menyajikan sop khas Makassar dengan cita rasa gurih."
}

### Delete Alternatif
DELETE https://web-gdss.vercel.app/api/alternatif
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "id_alternatif":"691180fb65de5d03ecbd1f40"
}

### Get All Kriteria
GET https://web-gdss.vercel.app/api/kriteria
Authorization: Bearer {{accessToken}}
Content-Type: application/json

### Get Kriteria By Id User
GET https://web-gdss.vercel.app/api/kriteria/id/6910cb902e5b13934a3a9b67
Authorization: Bearer {{accessToken}}

### Get Kriteria By Tipe
GET https://web-gdss.vercel.app/api/kriteria/tipe/benefit
Authorization: Bearer {{accessToken}}

### Get Total Kriteria
GET https://web-gdss.vercel.app/api/kriteria/total
Authorization: Bearer {{accessToken}}

### Add Kriteria
POST https://web-gdss.vercel.app/api/kriteria
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
     "id_user": "69109c6a6a0c7a5786f4c696",
  "nama": "Biaya Transportasi",
  "tipe": "Cost",
  "bobot": 3.50,
  "nilai": "1 - Sangat Murah;2 - Murah;3 - Cukup Murah;4 - Mahal;5 - Sangat Mahal"
}

### Update Kriteria
PUT https://web-gdss.vercel.app/api/kriteria
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "id_kriteria":"69119912b6e1f71ce9ff893f",
    "id_user":"69109c6a6a0c7a5786f4c696",
    "nama":"Biaya Transportasi",
    "tipe":"Cost",
    "bobot":3.50,
    "nilai":"1 - Sangat Murah;2 - Murah;3 - Cukup Murah;4 - Mahal;5 - Sangat Mahal"
}

### Delete Kriteria
DELETE https://web-gdss.vercel.app/api/kriteria?id_kriteria=69147bdae8ff8e90ee22be6b
Authorization: Bearer {{accessToken}}

### Get All Penilaian
GET https://web-gdss.vercel.app/api/penilaian
Authorization: Bearer {{accessToken}}

### Get All Users
GET https://web-gdss.vercel.app/api/user/
Authorization: Bearer {{accessToken}}

### Get All Alternatif
GET https://web-gdss.vercel.app/api/alternatif
Authorization: Bearer {{accessToken}}

### Add Penilaian
POST https://web-gdss.vercel.app/api/penilaian
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "id_user":"6910cb902e5b13934a3a9b67",
    "tanggal_penilaian":"12/18/2025",
    "id_alternatif":"691181ba3ef5b13486fe838d",
    "nilai":"69121760082657540b47d526 - 2;69121798082657540b47d52d - 3;691217ce082657540b47d534 - 5;691217ed082657540b47d53a - 1;6912180c082657540b47d540 - 4;6912182e082657540b47d546 - 2;6912184a082657540b47d54c - 4;69121869082657540b47d552 - 3",
    "keterangan":""
}

### Delete Penilaian
DELETE https://web-gdss.vercel.app/api/penilaian
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "id_penilaian":"691211f58bdb3e5f2ed6a46a"
}

### PAGE HASIL INDIVIDU

### Get Inisial User
GET https://web-gdss.vercel.app/api/user/find/peran/69109c6a6a0c7a5786f4c696
Authorization: Bearer {{accessToken}}

### Perhitungan Topsis By Id User
GET https://web-gdss.vercel.app/api/penilaian/topsis/6910cb902e5b13934a3a9b67
Authorization: Bearer {{accessToken}}


### Perhitungan Borda
GET https://web-gdss.vercel.app/api/penilaian/borda
Authorization: Bearer {{accessToken}}

### Get Penilaian By Id User And Id Alternatif
GET http://localhost:5000/api/penilaian/individu?id_user=69109c6a6a0c7a5786f4c696&id_alternatif=69117ffc1088bc47c3a2e5fc
Authorization: Bearer {{accessToken}}

### Get Laporan Penilaian
GET http://localhost:5000/api/penilaian/laporan
Authorization: Bearer {{accessToken}}