
### Login
POST https://web-gdss.vercel.app/api/auth/login
Content-Type: application/json

{
    "email":"arham@gmail.com",
    "password":"password2"
}

### Register
POST https://web-gdss.vercel.app/api/auth/register
Content-Type: application/json

{
    "nama":"Adam Fatin",
    "email":"adam@gmail.com",
    "password":"password",
    "peran":"Decision Maker 1"
}

### Logout
POST https://web-gdss.vercel.app/api/auth/logout

### Refresh Access Token
POST https://web-gdss.vercel.app/api/auth/refresh

### Token
@accessToken= eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF91c2VyIjoiNjkxMDljNmE2YTBjN2E1Nzg2ZjRjNjk2IiwibmFtYSI6IkRlY2lzaW9uIE1ha2VyIDEiLCJlbWFpbCI6ImFyaGFtQGdtYWlsLmNvbSIsInBlcmFuIjoiS2VwYWxhIERpbmFzIFBhcml3aXNhdGEiLCJ0Z2xfYmVyZ2FidW5nIjoiMjAyNS0xMS0wOVQxMzo1MTozOC41MDFaIiwiaWF0IjoxNzY1MjYzNTc4LCJleHAiOjE3NjUyNjcxNzh9.1hYK-jSKQ7lRK9AuSIjSLS34fBkvSkD0KkzeHPuWOpo

### Dashboard
GET https://web-gdss.vercel.app/api/
Authorization: Bearer {{accessToken}}



### Get User By Id
GET https://web-gdss.vercel.app/api/user/find?id_user=6910cb902e5b13934a3a9b67
Authorization: Bearer {{accessToken}}

### Get Total User
GET https://web-gdss.vercel.app/api/user/total
Authorization: Bearer {{accessToken}}

### Update User By Id   
PUT https://web-gdss.vercel.app/api/user
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "id_user":"69109c6a6a0c7a5786f4c696",
    "nama":"Nachsyas Arham Mumtaz",
    "email":"arham@gmail.com",
    "peran":"Decision Maker 1"
}

### Create New User
POST https://web-gdss.vercel.app/api/user
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "nama":"Reza Kurnia",
    "email":"reza@gmail.com",
    "password":"password",
    "peran":"Decision Maker 4"
}

### Delete User
DELETE https://web-gdss.vercel.app/api/user?id_user=6910cb372e5b13934a3a9b56
Authorization: Bearer {{accessToken}}

### Update Password
POST https://web-gdss.vercel.app/api/user/password
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "id_user":"69109c6a6a0c7a5786f4c696",
    "password":"password2"
}

### Get Total Alternatif
GET https://web-gdss.vercel.app/api/alternatif/total
Authorization: Bearer {{accessToken}}

### Add Alternatif
POST https://web-gdss.vercel.app/api/alternatif
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "nama":"Mie Titi Panakkukang",
    "deskripsi":"Mie kering khas Makassar favorit wisatawan."
}

### Update Alternatif
PUT https://web-gdss.vercel.app/api/alternatif
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "id_alternatif":"69117a7691a69d09370572a1",
    "nama":"Sop Saudara Irian",
    "deskripsi":"Menyajikan sop khas Makassar dengan cita rasa gurih."
}

### Delete Alternatif
DELETE https://web-gdss.vercel.app/api/alternatif
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "id_alternatif":"6925b19c9cceee509fbe7219"
}

### Get All Kriteria
GET http://web-gdss.vercel.app/api/kriteria
Authorization: Bearer {{accessToken}}
Content-Type: application/json

### Get Kriteria By Id User
GET https://web-gdss.vercel.app/api/kriteria/id/69109c6a6a0c7a5786f4c696
Authorization: Bearer {{accessToken}}

### Get Kriteria By Tipe
GET https://web-gdss.vercel.app/api/kriteria/tipe/benefit
Authorization: Bearer {{accessToken}}

### Get Total Kriteria
GET https://web-gdss.vercel.app/api/kriteria/total
Authorization: Bearer {{accessToken}}

### Add Kriteria
POST http://web-gdss.vercel.app/api/kriteria
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "nama": "Biaya Transportasi",
  "tipe": "Cost",
  "bobot": 3.50,
  "nilai": "1 - Sangat Murah;2 - Murah;3 - Cukup Murah;4 - Mahal;5 - Sangat Mahal"
}

### Update Kriteria
PUT https://web-gdss.vercel.app/api/kriteria
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "id_kriteria":"69121869082657540b47d552",
    "nama":"Waktu Operasional",
    "tipe":"Benefit",
    "bobot":12.50,
    "nilai":"1-Pagi; 2-Pagi & Siang; 3-Pagi, Siang & Sore; 4-Pagi, Siang, Sore & Malam"
}

### Delete Kriteria
DELETE http://localhost:5000/api/kriteria?id_kriteria=692559d5341a5e194f7131f6
Authorization: Bearer {{accessToken}}

### Get All Penilaian
GET http://localhost:5000/api/penilaian
Authorization: Bearer {{accessToken}}

### Get All Users
GET http://localhost:5000/api/user/
Authorization: Bearer {{accessToken}}

### Get All Alternatif
GET https://web-gdss.vercel.app/api/alternatif
Authorization: Bearer {{accessToken}}

### Add Penilaian
POST https://web-gdss.vercel.app/api/penilaian
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "id_user":"6910cb902e5b13934a3a9b67",
    "tanggal_penilaian":"11/28/2025",
    "id_alternatif":"6925b836d20af6b695dd05c4",
    "nilai":"69121798082657540b47d52d - 1;69255a20a14a7c851ccd5dca - 3;691217ce082657540b47d534 - 5;691217ed082657540b47d53a - 1;6912180c082657540b47d540 - 4;6912182e082657540b47d546 - 2;6912184a082657540b47d54c - 4;69121869082657540b47d552 - 3",
    "keterangan":""
}

### Delete Penilaian
DELETE http://localhost:5000/api/penilaian
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "id_penilaian":"691211f58bdb3e5f2ed6a46a"
}

### PAGE HASIL INDIVIDU

### Get Inisial User
GET https://web-gdss.vercel.app/api/user/find/peran/69109c6a6a0c7a5786f4c696
Authorization: Bearer {{accessToken}}

### Get All Decision Maker
http://localhost:5000/api/user/find/dm
Authorization: Bearer {{accessToken}}

### Perhitungan Topsis By Id User
GET http://localhost:5000/api/penilaian/topsis/6910cb902e5b13934a3a9b67
Authorization: Bearer {{accessToken}}


### Perhitungan Borda
GET http://web-gdss.vercel.app/api/penilaian/borda
Authorization: Bearer {{accessToken}}

### Get Penilaian By Id User And Id Alternatif
GET https://web-gdss.vercel.app/api/penilaian/individu?id_user=6910cb902e5b13934a3a9b67&id_alternatif=6925b81bd20af6b695dd0572
Authorization: Bearer {{accessToken}}

### Get Laporan Penilaian
GET http://web-gdss.vercel.app/api/penilaian/laporan
Authorization: Bearer {{accessToken}}